### ISSUE TITLE
IE not supported

### ISSUE THREAD

**Issue by RainerW** [Seitenbau/Sonferenz#37]
Layout get's totally freaked out after some clicks.

**Comment by ThomasR** [comment]
You mean IE<=8, right? That's because it's not capable of CSS3 selectors. So the crazy table-layout trickery does not work there.

**Comment by RainerW** [comment]
Hm, this would explain why my home system works.

**Comment by jschroeter** [comment]
added some fixes, IE8 is supported
IE 6 & 7 support won't be added
