### ISSUE TITLE
Custom user text after login

### ISSUE THREAD

**Issue by RainerW** [Seitenbau/Sonferenz#53]
After a user is logged in the "Welcome" Screen should be user specific.

Quick:
- define custom key for "home" when user is logged in.
- Click on Icon -> default "Home" 
- Click on "Konferenz" -> User "Home"

**Comment by toxisch** [comment]
New:
After login the conference button is replaced with info button. The info button links a new static page "info"!

**Comment by toxisch** [comment]
Use the key "page.info" to setup the text for new info page!
