### ISSUE TITLE
Talk Voring max is fix set to 10

### ISSUE THREAD

**Issue by chbaranowski** [Seitenbau/Sonferenz#96]
In the class ListVotesPanel2 line 71 is the max count set to 10.

```
@SpringBean
StaticContentService content2;

// FIXME: MAX
int max = 10;
```

https://github.com/Seitenbau/Sonferenz/blob/master/sonferenz-web/src/main/java/de/bitnoise/sonferenz/web/pages/voting/ListVotesPanel2.java

**Comment by RainerW** [comment]
fixed, is now 12

**Comment by kistenjunge** [comment]
caused a very peculiar behavior. +1 for the quick fix!!!
